controller_list:
  - name: fake_manipulator_controller
    joints:
      - yaska3_joint_1_s
      - yaska3_joint_2_l
      - yaska3_joint_3_u
      - yaska3_joint_4_r
      - yaska3_joint_5_b
      - yaska3_joint_6_t
initial:  # Define initial robot poses.
  - group: DN1P
    pose: home
