controller_list:
  - name: DN1P_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - yaska3_joint_1_s
      - yaska3_joint_2_l
      - yaska3_joint_3_u
      - yaska3_joint_4_r
      - yaska3_joint_5_b
      - yaska3_joint_6_t
  - name: yaskawa3_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - end_effector_adaptater_mors2
      - end_effector_mors1