controller_list:
  - name: fake_DN1P_controller
    type: $(arg fake_execution_type)
    joints:
      - staubli_joint1
      - staubli_joint2
      - staubli_joint3
      - staubli_joint4
      - staubli_joint5
      - staubli_joint6
initial:  # Define initial robot poses per group
  - group: DN1P
    pose: home