controller_list:
  - name: DN1P_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - staubli_joint1
      - staubli_joint2
      - staubli_joint3
      - staubli_joint4
      - staubli_joint5
      - staubli_joint6