controller_list:
  - name: fake_DN1P_controller
    type: $(arg fake_execution_type)
    joints:
      - yaska4_joint_1_s
      - yaska4_joint_2_l
      - yaska4_joint_3_u
      - yaska4_joint_4_r
      - yaska4_joint_5_b
      - yaska4_joint_6_t
  - name: fake_yaskawa4_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - end_effector_adaptater_mors1
      - end_effector_adaptater_mors2
initial:  # Define initial robot poses per group
  - group: DN1P
    pose: home
  - group: yaskawa4_hand
    pose: Close