arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - yaska4_joint_1_s
    - yaska4_joint_2_l
    - yaska4_joint_3_u
    - yaska4_joint_4_r
    - yaska4_joint_5_b
    - yaska4_joint_6_t
  gains:
    yaska4_joint_1_s:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yaska4_joint_2_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yaska4_joint_3_u:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yaska4_joint_4_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yaska4_joint_5_b:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yaska4_joint_6_t:
      p: 100
      d: 1
      i: 1
      i_clamp: 1