controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - yaska4_joint_1_s
      - yaska4_joint_2_l
      - yaska4_joint_3_u
      - yaska4_joint_4_r
      - yaska4_joint_5_b
      - yaska4_joint_6_t
  - name: hand_controller
    action_ns: gripper_action
    type: GripperCommand
    default: True
    joints:
      - end_effector_adaptater_mors1
      - end_effector_adaptater_mors2