# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  kuka_joint_a1:
    has_velocity_limits: true
    max_velocity: 6.283185307179586
    has_acceleration_limits: false
    max_acceleration: 0
  kuka_joint_a2:
    has_velocity_limits: true
    max_velocity: 5.235987755982989
    has_acceleration_limits: false
    max_acceleration: 0
  kuka_joint_a3:
    has_velocity_limits: true
    max_velocity: 6.283185307179586
    has_acceleration_limits: false
    max_acceleration: 0
  kuka_joint_a4:
    has_velocity_limits: true
    max_velocity: 6.649704450098396
    has_acceleration_limits: false
    max_acceleration: 0
  kuka_joint_a5:
    has_velocity_limits: true
    max_velocity: 6.771877497737998
    has_acceleration_limits: false
    max_acceleration: 0
  kuka_joint_a6:
    has_velocity_limits: true
    max_velocity: 10.73377489976513
    has_acceleration_limits: false
    max_acceleration: 0
  staubli_joint1:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  staubli_joint2:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  staubli_joint3:
    has_velocity_limits: true
    max_velocity: 5.5
    has_acceleration_limits: false
    max_acceleration: 0
  staubli_joint4:
    has_velocity_limits: true
    max_velocity: 7.1
    has_acceleration_limits: false
    max_acceleration: 0
  staubli_joint5:
    has_velocity_limits: true
    max_velocity: 5.5
    has_acceleration_limits: false
    max_acceleration: 0
  staubli_joint6:
    has_velocity_limits: true
    max_velocity: 12.2
    has_acceleration_limits: false
    max_acceleration: 0
  yaska3_joint_1_s:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: false
    max_acceleration: 0
  yaska3_joint_2_l:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: false
    max_acceleration: 0
  yaska3_joint_3_u:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  yaska3_joint_4_r:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  yaska3_joint_5_b:
    has_velocity_limits: true
    max_velocity: 4.36332312999
    has_acceleration_limits: false
    max_acceleration: 0
  yaska3_joint_6_t:
    has_velocity_limits: true
    max_velocity: 4.36332312999
    has_acceleration_limits: false
    max_acceleration: 0
  yaska4_joint_1_s:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: false
    max_acceleration: 0
  yaska4_joint_2_l:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: false
    max_acceleration: 0
  yaska4_joint_3_u:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  yaska4_joint_4_r:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  yaska4_joint_5_b:
    has_velocity_limits: true
    max_velocity: 4.36332312999
    has_acceleration_limits: false
    max_acceleration: 0
  yaska4_joint_6_t:
    has_velocity_limits: true
    max_velocity: 4.36332312999
    has_acceleration_limits: false
    max_acceleration: 0