yaska4_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - yaska4_joint_1_s
    - yaska4_joint_2_l
    - yaska4_joint_3_u
    - yaska4_joint_4_r
    - yaska4_joint_5_b
    - yaska4_joint_6_t
  gains:
    yaska4_joint_1_s:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yaska4_joint_2_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yaska4_joint_3_u:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yaska4_joint_4_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yaska4_joint_5_b:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yaska4_joint_6_t:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
yaska3_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - yaska3_joint_1_s
    - yaska3_joint_2_l
    - yaska3_joint_3_u
    - yaska3_joint_4_r
    - yaska3_joint_5_b
    - yaska3_joint_6_t
  gains:
    yaska3_joint_1_s:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yaska3_joint_2_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yaska3_joint_3_u:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yaska3_joint_4_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yaska3_joint_5_b:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yaska3_joint_6_t:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
kuka_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - kuka_joint_a1
    - kuka_joint_a2
    - kuka_joint_a3
    - kuka_joint_a4
    - kuka_joint_a5
    - kuka_joint_a6
  gains:
    kuka_joint_a1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kuka_joint_a2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kuka_joint_a3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kuka_joint_a4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kuka_joint_a5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kuka_joint_a6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
staubli_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - staubli_joint1
    - staubli_joint2
    - staubli_joint3
    - staubli_joint4
    - staubli_joint5
    - staubli_joint6
  gains:
    staubli_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    staubli_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    staubli_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    staubli_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    staubli_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    staubli_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1