controller_list:
  - name: yaska4_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - yaska4_joint_1_s
      - yaska4_joint_2_l
      - yaska4_joint_3_u
      - yaska4_joint_4_r
      - yaska4_joint_5_b
      - yaska4_joint_6_t
  - name: yaska3_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - yaska3_joint_1_s
      - yaska3_joint_2_l
      - yaska3_joint_3_u
      - yaska3_joint_4_r
      - yaska3_joint_5_b
      - yaska3_joint_6_t
  - name: kuka_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - kuka_joint_a1
      - kuka_joint_a2
      - kuka_joint_a3
      - kuka_joint_a4
      - kuka_joint_a5
      - kuka_joint_a6
  - name: staubli_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - staubli_joint1
      - staubli_joint2
      - staubli_joint3
      - staubli_joint4
      - staubli_joint5
      - staubli_joint6