# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: DN1P
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - yaska4_joint_1_s
    - yaska4_joint_2_l
    - yaska4_joint_3_u
    - yaska4_joint_4_r
    - yaska4_joint_5_b
    - yaska4_joint_6_t
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: ""
    action_ns: yaska4/joint_trajectory_action
    type: FollowJointTrajectory
    joints: [yaska4_joint_1_s, yaska4_joint_2_l, yaska4_joint_3_u, yaska4_joint_4_r, yaska4_joint_5_b, yaska4_joint_6_t]