DN1P_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - kuka_joint_a1
    - kuka_joint_a2
    - kuka_joint_a3
    - kuka_joint_a4
    - kuka_joint_a5
    - kuka_joint_a6
  gains:
    kuka_joint_a1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kuka_joint_a2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kuka_joint_a3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kuka_joint_a4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kuka_joint_a5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kuka_joint_a6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
kuka_hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - KGG_laison2
    - KGG_liaison1
  gains:
    KGG_laison2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    KGG_liaison1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1