controller_list:
  - name: fake_DN2P1_controller
    type: $(arg fake_execution_type)
    joints:
      - staubli_joint_1
      - staubli_joint_2
      - staubli_joint_3
      - staubli_joint_4
      - staubli_joint_5
      - staubli_joint_6
  - name: fake_staubli_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - end_effector_adaptater1
      - end_effector_adaptater2
initial:  # Define initial robot poses per group
  - group: DN2P1
    pose: home
  - group: staubli_hand
    pose: Close