DN1P_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - staubli_joint_1
    - staubli_joint_2
    - staubli_joint_3
    - staubli_joint_4
    - staubli_joint_5
    - staubli_joint_6
  gains:
    staubli_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    staubli_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    staubli_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    staubli_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    staubli_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    staubli_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1