controller_list:
  - name: DN2P1_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - staubli_joint_1
      - staubli_joint_2
      - staubli_joint_3
      - staubli_joint_4
      - staubli_joint_5
      - staubli_joint_6
  - name: staubli_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - end_effector_adaptater1
      - end_effector_adaptater2